spring.application.name=demo
server.port=7070

spring.jpa.hibernate.ddl-auto=update
#spring.datasource.initialization-mode=always
spring.datasource.url=jdbc:mysql://localhost:3306/demo
spring.datasource.username=hbstudent
spring.datasource.password=hbstudent
spring.jpa.show-sql=false

#server.tomcat.connection-timeout=30s  
#server.servlet.session.timeout=30m  
#spring.mvc.async.request-timeout=30000  


spring.datasource.hikari.maximum-pool-size=30
spring.datasource.hikari.connectionTimeout=30000 
spring.datasource.hikari.idleTimeout=600000  
spring.datasource.hikari.maxLifetime=1800000 